name: Test PlayBuffer Executable

on:
  workflow_run:
    workflows: ["Build and Release PlayBuffer"]
    types:
      - completed

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Download PlayBuffer artifact
        uses: actions/download-artifact@v4
        with:
          name: play_buffer-linux
          path: ./artifacts
      - name: Generate test sine wave
        run: |
          python3 -c "import numpy as np; np.array([np.sin(2*np.pi*440*t/44100) for t in range(44100)], dtype='float32').tofile('test.raw')"
      - name: Run PlayBuffer and check output
        run: |
          ./artifacts/play_buffer_linux < test.raw > output.txt
          grep "Playing 44100 samples" output.txt
  test-macos:
    runs-on: macos-latest
    steps:
      - name: Download PlayBuffer artifact
        uses: actions/download-artifact@v4
        with:
          name: play_buffer_macos
          path: ./artifacts
      - name: Generate test sine wave
        run: |
          python3 -c "import numpy as np; np.array([np.sin(2*np.pi*440*t/44100) for t in range(44100)], dtype='float32').tofile('test.raw')"
      - name: Run PlayBuffer and check output
        run: |
          ./artifacts/play_buffer_macos < test.raw > output.txt
          grep "Playing 44100 samples" output.txt
  test-windows:
    runs-on: windows-latest
    steps:
      - name: Download PlayBuffer artifact
        uses: actions/download-artifact@v4
        with:
          name: play_buffer_windows
          path: ./artifacts
      - name: Generate test sine wave
        run: |
          python -c "import numpy as np; np.array([np.sin(2*np.pi*440*t/44100) for t in range(44100)], dtype='float32').tofile('test.raw')"
      - name: Run PlayBuffer and check output
        run: |
          .\artifacts\play_buffer_windows.exe < test.raw > output.txt
          findstr "Playing 44100 samples" output.txt
        shell: cmd
